In [2]:
import numpy

a = numpy.array([[1, 2], [4, -1]])
b = numpy.array([[2, -3],[-4, 1]])

print(a@b-b@a)

[[ 4 -8]
 [12 -4]]


In [3]:
a = numpy.array([[-1, 2], [0, 1]])
print(a@a)

[[1 0]
 [0 1]]


In [4]:
a = numpy.array([[3, 5], [6, -1]])
b = numpy.array([[2, 1],[-3, 2]])

print(a@b)

[[-9 13]
 [15  4]]


In [5]:
a = numpy.array([[2, 3, 4],[1, 0, 6],[7, 8, 9]])

print(numpy.linalg.det(a))

35.00000000000001


In [6]:
a = numpy.array([[2, 3, 4, 1],[1, 2, 3, 4],[3, 4, 2, 1],[4, 1, 2, 3]])

print(numpy.linalg.det(a))

-119.99999999999997


In [7]:
a = numpy.array([[1, 2, -3],[0, 1, 2],[0, 0, 1]])

print(numpy.linalg.inv(a))

[[ 1. -2.  7.]
 [ 0.  1. -2.]
 [ 0.  0.  1.]]


In [8]:
a = numpy.array([[1, 2, 3 ,4], [3, -1, 2, 5], [1, 2, 3, 4], [1, 3, 4, 5]])

print(numpy.linalg.matrix_rank(a))

2


In [10]:
a = numpy.array([[3, 2, 1],
                 [2, -1, 1],
                 [1, 5, 0]])

b = numpy.array([5, 6, -3])

def matrix_method(a, b):
    det_a = numpy.linalg.det(a)

    if det_a == 0:
        print("Система має або нескінченно багато рішень, або немає рішень.")
    else:
        a_inv = numpy.linalg.inv(a)

        solutions = numpy.dot(a_inv, b)
    return solutions

def kramer_method(coeff_matrix, rhs_vector):
    det_main = numpy.linalg.det(coeff_matrix)

    solutions = []

    for i in range(coeff_matrix.shape[1]):
        temp_matrix = numpy.copy(coeff_matrix)
        temp_matrix[:, i] = rhs_vector
        det_temp = numpy.linalg.det(temp_matrix)
        solution = det_temp / det_main
        solutions.append(round(solution, 1))

    return solutions
print(f"Метод Крамера: {kramer_method(a, b)}")
print(f"Матричний метод: {matrix_method(a, b)}")
print(f"Перевірка рішення: {numpy.linalg.solve(a, b)}")

Метод Крамера: [2.0, -1.0, 1.0]
Матричний метод: [ 2. -1.  1.]
Перевірка рішення: [ 2. -1.  1.]


In [11]:
a = numpy.random.randint(10, size=(4, 5))
print(f"Матриця:\n{a}")
print(f"Середні значення для стовпців: {numpy.mean(a, axis=0)}")
print(f"Середні значення для рядків{numpy.mean(a, axis=1)}")


Матриця:
[[8 8 9 3 3]
 [9 2 6 4 6]
 [3 5 2 4 1]
 [8 4 6 1 9]]
Середні значення для стовпців: [7.   4.75 5.75 3.   4.75]
Середні значення для рядків[6.2 5.4 3.  5.6]
